### PR TITLE
update for swift 2.2

### PR DESCRIPTION
**Pull request by sairamkotha**

### CODE REVIEW

**Comment by serejahh** [comment]
@sairamkotha Thanks for contribution. Remove your user data and lgtm

**Comment by sairamkotha** [comment]
Now please check  @serejahh I removed user data

**Comment by serejahh** [comment]
@sairamkotha `SideMenu.xcodeproj/xcuserdata/tech-amber.xcuserdatad/xcschemes/xcschememanagement.plist` is still under source control. Please add `xcuserdata/` to gitignore and remove your data from the repo

**Comment by sairamkotha** [comment]
Please check now removed all kinds of user data from project.

**Comment by sairamkotha** [comment]
You can merge now

**Comment by serejahh** [comment]
@sairamkotha Added in version 1.2.1. Please, update. Feel free to send us a bug report or a feature request. Thank you!

**Pull request closed without merging**
